# Generated by Django 5.1.6 on 2025-04-27 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('plaform', models.CharField(choices=[('android', 'Mobile App - Android'), ('iphone', 'Mobile App - iPhone'), ('windows', 'Desktop - Windows'), ('linux', 'Desktop - Linux'), ('mac', 'Desktop - Mac'), ('webapp', 'Web App'), ('bot', 'Bot'), ('script', 'Script')], max_length=20)),
                ('tags', models.JSONField(default=list)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
