# Generated by Django 5.1.6 on 2025-04-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='plaform',
            field=models.CharField(choices=[('mobileapp', 'Mobile App'), ('desktop', 'Desktop'), ('webapp', 'Web App'), ('bot', 'Bot'), ('script', 'Script')], max_length=20),
        ),
    ]
