# Generated by Django 5.1.6 on 2025-04-29 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_alter_bookmark_plaform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='order_index',
        ),
    ]
