# Generated by Django 5.1.6 on 2025-04-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_remove_bookmark_order_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='plaform',
            field=models.CharField(choices=[('Mobile', 'Mobile App'), ('Desktop', 'Desktop'), ('Web', 'Web App'), ('Bot', 'Bot'), ('Script', 'Script')], max_length=20),
        ),
    ]
