# Generated by Django 5.1.6 on 2025-05-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0004_alter_bookmark_plaform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='plaform',
            new_name='platform',
        ),
    ]
